name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: -v ${{ env.JAVA_HOME_11_X64 }}:/root/.jdks/jdk11
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
